### ISSUE TITLE
Randomly added 11693.2 thieving xp upon ticking off Beneath Cursed Tides

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#11]
I verified all my xp prior to starting the quest by manually comparing it against ingame, made sure there was zero discrepancies (despite the decimal places as those don't show ingame). I had 1670xp in thieving. I completed Beneath Cursed Tides ingame. I dont believe there is any point in the quest that would have given me thieving xp. Upon clicking Beneath Cursed Tides, and then recalc, Troll Stronghold appeared on top, which I thought was interesting cause it wasn't the next achievement listed before the calc. Upon looking at the requirements, it requires 30 thief. I only had 12. Check my thieving xp in PT and it was 13363.2xp. I have no idea how this happened. I checked qualities and could not find anything else that ticked off by accident. The xp lamp from the quest said to use on Herblore which I did. And that added the xp in the skills column correctly. So it didnt add thief xp instead of herblore xp, same with the other lamps. All the other skills were exactly correct ingame vs PT. Only thieving xp was increased. Also I adjusted the thieving xp to 1670 and recalced and it still wants me to do Troll Stronghold but now I have to steal from cake stall for 1.1 hours. Surely thats not the best option right now I would guess. But that's another issue entirely, unless the former thief xp of 13k xp that originally got it to the top is still input somewhere.

**Comment by RenegadeLucien** [comment]
Alright, so first thing to note is that 13363 XP = LV30, so Project Tenacity appeared to bring your Thieving level to 30.

What actually seems to be happening here is that simply selecting Troll Stronghold will make your player table display 30 Thieving. As part of the time calculation for an achievement, Project Tenacity will level your player up to meet the requirements, then reset it. If you were to recalc right then and there, the extra Thieving exp would no longer have shown. But for some reason the skill tab isn't resetting. Not sure exactly why this is happening, will have to look into this more.

As for Troll Stronghold being suboptimal, I'm not entirely sure of that. The reason Troll Stronghold would have gotten high priority is because it rewards two large lamps with a LV30 skill requirement. Presumably completing Beneath Cursed Tides would have leveled a slow skill above LV30, making Troll Stronghold a much higher priority target than it would have been before completing Beneath Cursed Tides.

**Comment by RenegadeLucien** [comment]
Figured it out---turns out I was not redisplaying the player table on selecting an achievement, since I didn't know it was necessary to avoid issues like this one. This has been fixed, and will be included in v0.7.2b.
