### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by Californ1a** [RenegadeLucien/project-tenacity#15]
Likely most of these are already on your radar, but I'd like to list them out just in case there's 1 or 2 you haven't considered.

---

* Attempting to complete an achievement requires having to recalc and redraw the entire interface.
  * Because of that, the achievement list scrolls back up to the top and un-does any sorting you did on any of the various tables (from clicking any of the column headers).
  * There's a ~12min wait time to complete an achievement (recalc/redraw).

* You can't complete multiple achievements at once (only able to select one at a time).
  * When you first create the profile, there's going to be a ton of achievements you want to mark as complete before having to recalc.
  * There should either be tickboxes to select multiple, or allow ctrl-click/shift-click to select multiple.

* You can't select an achievement to mark as complete without the info dialog box opening.
  * A separate button in a third column would probably be better for opening the dialog box, possibly alongside another button to open your browser with the wiki page for that achievement.
  * There is a slight workaround to this, if you right-click and hold on an achievement, and drag onto another achievement, then the one you initially right-clicked on will stay selected without opening the dialog box.

* The save file is in a format you can't manually edit outside of the planner (json or xml seems like a much better solution? or even sqlite if you need to store a relational db).
  * Because of this, you can't really do any kind of workaround to manually input a bunch of completed achievements and then reopen the planner so it only has to recalc once.
  * Also, if someone wanted to take the save file data and build something else off of it, json, xml, or sqlite are much more universal (say for example someone wanted to make a webapp where you can import your planner save data, maybe to export in a rswiki userpage format, it would almost have to be in either json or xml for any kind of decent compatibility like this).

* There should be more sorting options for the achievements.
  * It would be much easier to browse them if they were in the same order as they are in-game with the sections and subsections rather than one long list.
  * There should be a search/filter for the achievement list.

* The experience column of the skills tab shouldn't use scientific notion
  * There should be commas or periods (depending on locale) for any numbers anywhere (quantity in bank, effective time cost of achievements, etc.).
  * There should also be a level column with a virtual levels toggle on the skills tab.

* When hitting enter after typing in data for a new row at the bottom, it should insert the new row.
  * Likewise, hitting enter after typing in the experience field for the xp lamp calculator should hit calculate.
  * Selecting a row in the bank, weapons, armour, or qualities tabs and hitting Del (possibly backspace as well) on the keyboard should remove the row.

* The skills tab shouldn't need to scroll for the last two hidden rows, there's plenty of whitespace under the table to display them, unless you're planning on using that whitespace for other buttons/fields.

**Comment by RenegadeLucien** [comment]
Oh man, let me address these one at a time =P

-So there's not much I can do about recalculating the table on every achievement, as it has to do that to keep the list accurate at all times. However, I agree that it shouldn't undo all sorting done on each tab.

-Is it really taking 12 minutes to complete a single achievement? I've never seen it take more than 2 locally. Only way it should take 12 minutes is if you're deleting the gedata file on every achievement, which is not necessary and I doubt is what's going on here.

-Completing multiple achievements is definitely on my to-do list. At the moment you can (somewhat) get around this by completing big meta-achievements that have dozens of lesser achievements as requirements (e.g. Completionist Cape, Task Master, Master Quester) but this is not an ideal solution.

-Yeah, opening the dialog box every time can get pretty annoying (even to me during testing =) so making that an option in some way is on my to-do list.

-So, the save file. Doing something with that save is _definitely_ something I want to deal with before release, not only because it's a jumbled mess of characters, but also because as it currently is it's _incredibly_ easy to break with updates. Haven't decided what I want to convert it to yet, but JSON/XML are both pretty good ideas.

-Adding the in-game categories to the achievements...I can do that...but it would take some time because I'd have to add metadata to all nearly 3,000 achievements in the database. Not to mention, some of the achievements in the database (e.g. quests) aren't actually full achievements in the game but are more stepping stones, so they wouldn't really have a category.

-Search function is definitely on my list...not sure what you'd want out of a filter function though. What would you want to filter by? Or does this piggyback off of the last issue, where you'd want the sections/subsections added and filter by those?

-No scientific notation. Yep, definitely going to be addressed.

-As is adding place separators.

-And a level column. This in particular is right near the top of my list, since I know no one wants to have a level table up all the time when using Project Tenacity =P

-Using enter/delete to insert/delete rows in the player data tabs will be added in before release.

-I didn't stretch the skills tab to fill the whitespace at the bottom because I wanted to keep all the tabs the same size (other tabs, like the bank tab, do need that white space for buttons.) But I gather that not having to scroll the skills tab all the time is more important than having the tabs different sizes. Will be addressed.

So if you don't mind, I'm going to split this issue into several smaller ones just to make it more workable. If you have further questions/comments on any of them, feel free to continue the discussion there =)

**Comment by RenegadeLucien** [comment]
All issues have been separated into their own tasks, closing this one.
