### ISSUE TITLE
Achievements not ticked off correctly

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#2]
The loaded achievements are not correctly ticked off. Including skill related achievements "Hunter 10, 20 etc" even though my exp loaded correctly.

**Comment by RenegadeLucien** [comment]
I'm assuming you see "0.0" in the time cost column for the skill achievements you have surpassed?

At this moment, the skill achievements aren't directly tied to RuneMetrics like the quests are, so they are not completed automatically. This wasn't a planned feature of Project Tenacity, but since these achievements complete automatically once you reach the skill level, they really should be auto-completed--I'll see what I can do on that front.

Are there any achievements other than the skill achievements that you have noticed this for?

**Comment by CoincidalRS** [comment]
Actually they are a negative number, but its not consistent. Right now Im looking at it and "Dorics task 8" is at  -1.30926..., which is a task I've completed. While is "Brother in More Arms" is -0.63763..." which is a task I have not completed. It occurred to me while typing this I was somehow thinking it would magically get ALL achievement data, I understand it is just quests and follows your questing method of lvl 3 to max/comp/trim etc. As well as the negative numbers representing that you will effectively save time elsewhere by completing these tasks. That was my misunderstanding when I read the readme. To answer your question no there was no other tasks similiar to the skills ones.

**Comment by RenegadeLucien** [comment]
That is indeed what is meant by a negative time cost (positive time save.) Unfortunately, I cannot get any achievement data aside from quests and skills, because there is no RuneMetrics API for achievement data, so everything else has to be user-managed. There's no way around that.

That leaves the skill achievements, which I still plan to update so they complete automatically on reaching a certain skill level, but I'm going to downgrade this to T80 since it doesn't really produce any incorrect information (at least, nothing that could result in an incorrect achievement path.)

**Comment by RenegadeLucien** [comment]
Skill-based achievements now auto-complete. Will be included in v0.7.1b.
