### ISSUE TITLE
When window is resized the buttons are inaccessible.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#3]
When the program window is resized all of the buttons will be hidden (the program size stays the same and doesn't resize down with the window). Of course this isn't too big of an issue, but there is also no scrolling feature so you can not access any buttons if you were to shorten the size of the window.

EDIT: Same exact thing in Achievement window pop ups. For the longer ones that fill the page. You can not scroll them so unless you have a massive computer screen can not read the entire achievement info.

**Comment by RenegadeLucien** [comment]
The very, very simple fix is just to make the window un-resizeable. If this is an acceptable solution, I can include it in with 0.7.1b. Making the stuff actually resize is a much bigger deal because everything is currently fixed-size. Changing this would take a lot more effort.

The achievement popups, on the other hand, already can (and should) be resized in order to read the whole popup if necessary.

**Comment by RenegadeLucien** [comment]
Window was made non-resizeable as part of v0.7.1b. If this is undesirable to you, feel free to open a new issue or reopen this one.
