### ISSUE TITLE
Incorrect list

### ISSUE THREAD

**Issue by RatGeezer** [RenegadeLucien/project-tenacity#37]
Hi,

I've just started using Project Tenacity with a fresh new Runescape account and its already trying to start me on quests such as 'The Dig Site' that has requirements of Lv 25 Thieving, Lv 10 Agility and Lv 10 Herblore, and 'Claiming the Knight's Experience' that has Lv 10 Mining, and 'Enakhra's Lament' that required Lv 45 Firemaking and Lv 50 Crafting - surely these should be further down the list? and the last couple of times that I have opened up Project Tenacity, it keeps pulling the wrong Mining Lv from my profile (I have Lv 1 Mining and twice it has said that I have Lv 10 and once Lv 7) - sorry if this is an issue that has already been posted but the list doesn't seem to be tailored to my account :/ 

Also, another issue I noticed - the 'complete assignment/recalc' and 'save progress' buttons are cut off the screen for me (see screenshot)
[Project Tenacity issue.docx](https://github.com/RenegadeLucien/project-tenacity/files/3444471/Project.Tenacity.issue.docx)

btw can I just say, thanks for undertaking this task man, you're a hero!

**Comment by RenegadeLucien** [comment]
Alright, let me address these one at a time.

I don't believe The Dig Site is misplaced. All of its prerequisites take very little time to complete, and it rewards 15,300 Mining experience, a skill that is very slow to train if you are at level 1. Thus, its place high up on the list is justified. You can use the detailed pop-up to see what actions it expects you to take to train each skill.

Enakhra's Lament might be misplaced, since it seems to be recommending training Firemaking with pitch cans even at very low Firemaking levels, which is probably a bug.

I'm not sure why it would keep loading the wrong Mining level from your profile. Could you send me your save file (the .ptp file)?

As for the buttons being cut off, what screen resolution are you using? If it is 1024x768 (or less) then part of the screen will be cut. This is known, and the only way to fix it is to make the screen resizeable, which I have tried and failed to do in the past.

**Comment by RatGeezer** [comment]
Hi,
Ah ok, ya that makes sense, I'm still new to how the list works - I think when I saw Lv 25 Thieving that I assumed it would be later in the list :P 

This may be a dumb question but where would I find the .ptp file?
My screen resolution is 1366x768 - has it been reported before for a higher screen resolution than 1024x768? 

Thanks for the quick reply man, I'm enjoying using Project Tenacity so far!
Many thanks,
Charlie
    On Tuesday, 30 July 2019, 01:03:27 BST, RenegadeLucien <notifications@github.com> wrote:  
 
 
Alright, let me address these one at a time.

I don't believe The Dig Site is misplaced. All of its prerequisites take very little time to complete, and it rewards 15,300 Mining experience, a skill that is very slow to train if you are at level 1. Thus, its place high up on the list is justified. You can use the detailed pop-up to see what actions it expects you to take to train each skill.

Enakhra's Lament might be misplaced, since it seems to be recommending training Firemaking with pitch cans even at very low Firemaking levels, which is probably a bug.

I'm not sure why it would keep loading the wrong Mining level from your profile. Could you send me your save file (the .ptp file)?

As for the buttons being cut off, what screen resolution are you using? If it is 1024x768 (or less) then part of the screen will be cut. This is known, and the only way to fix it is to make the screen resizeable, which I have tried and failed to do in the past.

**Comment by RatGeezer** [comment]
Hi,
Also, I have just noticed that it keeps pulling qualities that I haven't achieved ('honour points', 'penance queen', 'thaler', and 'barbarian assault collector rank 2') - has this bug been raised before? :/ half the qualities i have at the moment on project tenacity are ones that I havent actually achieved - this wuld affect my list right?

    On Wednesday, 31 July 2019, 20:38:14 BST, Charlie Deacon <deacc00139@yahoo.co.uk> wrote:  
 
  Hi,
Also, I have just noticed that it keeps pulling qualities that I haven't achieved ('honour points', 'penance queen', 'thaler', and 'barbarian assault collector rank 2') - has this bug been raised before? :/ half the qualities i have at the moment on project tenacity are ones that I havent actually achieved - this wuld affect my list right?

    On Wednesday, 31 July 2019, 20:36:39 BST, Charlie Deacon <deacc00139@yahoo.co.uk> wrote:  
 
  Hi,
Also, I have just noticed that it keeps pulling qualities that I haven't achieved ('honour points', 'penance queen', 'thaler', and 'barbarian assault collector rank 2') - has this bug been raised before? :/ half the qualities i have at the moment on project tenacity are ones that I havent actually achieved - this wuld affect my list right?

    On Wednesday, 31 July 2019, 19:04:23 BST, Charlie Deacon <deacc00139@yahoo.co.uk> wrote:  
 
  Hi,
Ah ok, ya that makes sense, I'm still new to how the list works - I think when I saw Lv 25 Thieving that I assumed it would be later in the list :P 

This may be a dumb question but where would I find the .ptp file?
My screen resolution is 1366x768 - has it been reported before for a higher screen resolution than 1024x768? 

Thanks for the quick reply man, I'm enjoying using Project Tenacity so far!
Many thanks,
Charlie
    On Tuesday, 30 July 2019, 01:03:27 BST, RenegadeLucien <notifications@github.com> wrote:  
 
 
Alright, let me address these one at a time.

I don't believe The Dig Site is misplaced. All of its prerequisites take very little time to complete, and it rewards 15,300 Mining experience, a skill that is very slow to train if you are at level 1. Thus, its place high up on the list is justified. You can use the detailed pop-up to see what actions it expects you to take to train each skill.

Enakhra's Lament might be misplaced, since it seems to be recommending training Firemaking with pitch cans even at very low Firemaking levels, which is probably a bug.

I'm not sure why it would keep loading the wrong Mining level from your profile. Could you send me your save file (the .ptp file)?

As for the buttons being cut off, what screen resolution are you using? If it is 1024x768 (or less) then part of the screen will be cut. This is known, and the only way to fix it is to make the screen resizeable, which I have tried and failed to do in the past.

**Comment by RenegadeLucien** [comment]
The .ptp file should be in the same folder as Project Tenacity itself (and the gedata.txt file it generates to store GE data.)

1366x768 will still encounter problems, because the height of your screen is the same as the height of Project Tenacity. In theory the whole screen should show up, but in practice the bottom 25-50 pixels get cut off, due to toolbars or some other system thing taking up the bottom. I'll try to make it resizable.

As for the extra qualities being pulled in, I have no idea why that would happen. Project Tenacity can't even pull in any qualities that aren't quests, miniquests, or skills. Did you happen to check off one of the Barbarian Assault achievements?

**Comment by RenegadeLucien** [comment]
Regarding Enakhra's Lament--this was indeed a bug. The calculator was not taking into account upfront cost for performing an action (e.g. buying a pitch can for Firemaking training.)

This has been fixed and the fix will be present in v1.0.2 on Friday.

**Comment by RenegadeLucien** [comment]
I'm going to close this, as it seems most of the issues identified here have been resolved with v1.0.3.

If you still encounter any issues, feel free to reopen this or create a new issue.
