### ISSUE TITLE
No Saradomin godsword?

### ISSUE THREAD

**Issue by poiklers** [RenegadeLucien/project-tenacity#41]
Can't seem to find the "Saradomin godsword" nor the "Saradomin godsword (passive)". Have type it multiple different ways and still can't find it. Nor, apparently, the Zamorak godsword and the Armadyl godsword. Bandos godsword works though,

**Comment by RenegadeLucien** [comment]
Yeah so about this...When I populated the databases for weapons and armour, I left out a lot of gear that has identical stats as other gear because the combat simulator still wasn't finished and I wanted it to run faster for testing. I guess I never got around to adding in what was left.

These in particular have been added, they will be included in v1.0.3 (in the meantime you can use a Bandos godsword as it has the same stats so the simulator treats it identically) but there are probably more. If you find any more, feel free to let me know.
