### ISSUE TITLE
Possible Time Cost Issue

### ISSUE THREAD

**Issue by Mr-Lasagne** [RenegadeLucien/project-tenacity#60]
Hi, the achievement Brothers in More Arms is at the top of my list above quests like River of Blood and Plague's End. I'll attach a screenshot of the path information. Another thing I'm confused about is in the path information for Brothers in More Arms it wants me to string adamant 2h crossbows and collect green charms. I saw somebody had a similar problem with Araxxor achievements appearing at the top so I'll try reinstalling but I figured I'd let you know about my possible issue anyway, cheers.

<img width="1680" alt="Possible Time Cost Issue" src="https://user-images.githubusercontent.com/58007311/74447368-265b2580-4e71-11ea-8dee-a68386b9db33.png">

**Comment by RenegadeLucien** [comment]
So the "killing the black dragons for green charms" thing really doesn't care about the green charms, it wants you to kill black dragons in order to reach 90 Defence (which you seem to be only a few thousand XP away from, hence the time being only 0.01 hours.) I'm not 100% sure what the deal is with the adamant 2h crossbows, but I believe it's for making money (since addy 2h crossbows are worth a lot more than the materials to make them--Project Tenacity doesn't take into account the accessibility of raw materials.)

The main issue here, though, is that the Brothers in More Arms achievements assumes you solo the ROTS encounter (and thus get all the XP from it), which is why it seems to be saving so much time (presumably, soloing ROTS six times in less than an hour would be far faster combat XP than whatever it thinks your fastest combat training method is.) 

Of course, most people aren't going to be soloing ROTS to complete this achievement. Updated the Brothers in More Arms achievement to assume party size of 4, this should mitigate this issue. This will be released in v1.0.9.

**Comment by RenegadeLucien** [comment]
v1.0.9 released.
