### ISSUE TITLE
Complete Achievements showing up as Incomplete

### ISSUE THREAD

**Issue by tbest31** [RenegadeLucien/project-tenacity#74]
When I put in my username and generate a new profile, two achievements are recommended to be completed first: the "Epi Logueque Experience" and "Deep and Bloody Experience." I have already completed these two achievements, however, and I have no way to remove them from the top of the list without adding their experience rewards to my skills, which doesn't actually reflect my actual skills since I have previously claimed these rewards. There may be more achievements like this, but these are the two I have noticed because they are at the top.

**Comment by RenegadeLucien** [comment]
Unfortunately, there's only RuneMetrics data available for quests and skills, not all achievements. Thus, Project Tenacity can only autocomplete quest and skill achievements.

In order to remove them from the top of the list, you can shift-click to complete several achievements at once. If multiple achievements are completed at once, their rewards will not be claimed as Project Tenacity will assume that you are checking off several achievements you had already completed.
