### ISSUE TITLE
Lists requirements in the popup I have already completed.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#9]
The example I tested is the Wilderness Set Task - Easy. I selected that I completed them and it automatically ticked off each individual task throughout the list as completed. I then went back and unticked off the task set in the qualities menu, and left the associated achievements ticked. And recalced. And it still said I need to completed each individual one. Then I thought maybe because it was previously ticked off and then unticked it could have messed with that portion of the system. So on brand new account, I manually ticked off the knights sword. Recalc'd, then checked claiming the knight experience and found it to still say the completing knights sword is a requirement. All of my info is coming from the Completion Path Info pop-up, under "To complete this task, you must fulfill the following..."

EDIT: After testing other types of requirements, I'm thinking that the requirements that are supposed to not appear when they've been completed are under the "This involves performing..." area. If this is the case then quests that are required do not appear if they've been marked as completed. As well as skill training methods (The required levels in the requirements section still are there, even if I have obtained those levels). The money making method is still there, specifically for troll stronghold which requires 12 coins. I added 12 coins to my PT bank and "picking potatoes" was still listed as a required action.

**Comment by RenegadeLucien** [comment]
It looks like there are two separate issues here: the "completed requirements are still shown in the achievement popup" and the "money making is always in the achievement popup." Let me address each individually...

The completed requirements bit is very simple. I forgot to include a filter on the list of requirements the achievement popup outputs and just print out everything instead. Easy fix.

The money making part is somewhat trickier, and this is based on an admittedly flawed design decision I made several months ago to _never_ mark money/item requirements as complete. Why? Because I didn't want Project Tenacity telling someone to empty their banks over a single achievement. At the time I didn't take into account two pretty important points:
 -that if Project Tenacity said to empty their bank, it means that the money is used more efficiently here than anywhere else, and
 -the really important stuff like weapons and armour aren't supposed to be in the bank anyway.

Because of this, I have decided to flip this decision and allow money/item requirements to be marked as complete again. Both of these changes are done and will be included in v0.7.2b.
